apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app-kubernetes
  template:
    metadata:
      labels:
        app: food-app-kubernetes
    spec:
      containers:
      - name: nextjs-container
        image: us.gcr.io/food-ordering-k8-433016/food-app-kubernetes:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
