apiVersion: v1
kind: Service
metadata:
  name: food-app-kubernetes-service
spec:
  type: LoadBalancer
  selector:
    app: food-app-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
